### ISSUE TITLE
propertyDatabase.db and propertyAliases.db files log errror 

### ISSUE THREAD

**Issue by phields** [Fydar/AssetIcons#48]
![image](https://user-images.githubusercontent.com/31947421/202104695-b0365986-f5a3-4afa-b94f-e5ad081ee356.png)
UnityVersion： 2021.3.12

**Comment by phields** [comment]
```csharp         [OnInspectorDispose]
        private void Save()
        {
            UnityEditor.EditorUtility.SetDirty(this);
            UnityEditor.AssetDatabase.SaveAssets();
            UnityEditor.AssetDatabase.Refresh();
        }
```
It may be related to this part of the code, not sure if it is Problem with AssetIcons

**Comment by Fydar** [comment]
The code snippet you linked isn't contained within AssetIcons.

I am unfamiliar with `propertyDatabase.db` and `propertAliases.db`; AssetIcons does not interact with these directly.

The callstack reveals no information which might be able to point towards the issue. I will install that Unity version and investigate further. 

It doesn't seem likely that this is an issue with AssetIcons.

Upon further investigation I can see other Unity users encountering a similar problem. From the suggestions from the Unity staff, it seems they suspect that the issue is caused by either a Source Control client reading the files or an antivirus scan.

https://forum.unity.com/threads/the-property-database-library-search-propertydatabase-db-is-already-opened.1285634/
